import Foundation
import Observation

@Observable
@MainActor
public final class ConfigStore {
    public var vault: String = ""
    public var ocrLang: String = "eng"
    public var dbPath: String = ""
    public var archivePath: String = ""
    public var inboxPath: String = ""
    public var customBinaryPath: String = ""
    
    private let configURL: URL
    
    public init() {
        let home = FileManager.default.homeDirectoryForCurrentUser
        self.configURL = home.appendingPathComponent(".config/symingest/config.toml")
        
        // Load from UserDefaults
        self.inboxPath = UserDefaults.standard.string(forKey: "SYMINGEST_INBOX_PATH") ?? ""
        self.customBinaryPath = UserDefaults.standard.string(forKey: "SYMINGEST_BINARY_PATH") ?? ""
        
        load()
    }
    
    public func load() {
        let home = FileManager.default.homeDirectoryForCurrentUser
        
        // Set defaults
        if dbPath.isEmpty {
            dbPath = home.appendingPathComponent(".local/share/symingest/symingest.db").path
        }
        if archivePath.isEmpty {
            archivePath = home.appendingPathComponent(".local/share/symingest/archive").path
        }
        
        guard FileManager.default.fileExists(atPath: configURL.path) else { return }
        
        do {
            let content = try String(contentsOf: configURL, encoding: .utf8)
            let lines = content.components(separatedBy: .newlines)
            for line in lines {
                let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
                if trimmed.isEmpty || trimmed.hasPrefix("#") { continue }
                
                let parts = trimmed.components(separatedBy: "=")
                guard parts.count >= 2 else { continue }
                let key = parts[0].trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
                
                // Join in case the value itself has an equals sign, then strip quotes
                let valRaw = parts[1...].joined(separator: "=").trimmingCharacters(in: .whitespacesAndNewlines)
                var val = valRaw
                if val.hasPrefix("\"") && val.hasSuffix("\"") {
                    val = String(val.dropFirst().dropLast())
                }
                
                switch key {
                case "vault":
                    self.vault = val
                case "ocr_lang":
                    self.ocrLang = val
                case "db_path":
                    self.dbPath = val
                case "archive_path":
                    self.archivePath = val
                default:
                    break
                }
            }
        } catch {
            print("Failed to load config: \(error)")
        }
    }
    
    public func save() {
        // Save UserDefaults
        UserDefaults.standard.set(inboxPath, forKey: "SYMINGEST_INBOX_PATH")
        UserDefaults.standard.set(customBinaryPath, forKey: "SYMINGEST_BINARY_PATH")
        
        // Generate TOML
        var lines: [String] = []
        lines.append("# symingest configuration generated by GUI")
        lines.append("vault = \"\(vault)\"")
        lines.append("ocr_lang = \"\(ocrLang)\"")
        lines.append("db_path = \"\(dbPath)\"")
        lines.append("archive_path = \"\(archivePath)\"")
        
        let fileManager = FileManager.default
        let dir = configURL.deletingLastPathComponent()
        
        do {
            if !fileManager.fileExists(atPath: dir.path) {
                try fileManager.createDirectory(at: dir, withIntermediateDirectories: true)
            }
            let toml = lines.joined(separator: "\n") + "\n"
            try toml.write(to: configURL, atomically: true, encoding: .utf8)
            print("Config saved to \(configURL.path)")
        } catch {
            print("Failed to save config: \(error)")
        }
    }
}
