version: "2"

linters:
  default: standard
  enable:
    - gocritic
    - gosec
    - misspell

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-tags:
        - style
        - experimental
        - opinionated

  exclusions:
    paths:
      - client
      - docs
      - scripts
      - .github
    rules:
      - path: _test\.go
        linters:
          - gosec
