package extract

import (
	"context"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"testing"
)

// generateAbuseFixtures builds the abuse corpus (zip bomb, entry flood, deep
// XML nesting) deterministically in dir. The fixtures are generated by this
// helper rather than committed as opaque binaries; the tests below are the
// regression net for the decompression-limit work.
func generateAbuseFixtures(t *testing.T, dir string) map[string]string {
	t.Helper()
	// Zip bomb: a single entry whose decompressed size exceeds the per-entry
	// cap. Highly compressible, tiny on disk, 32 MiB+1 in memory.
	bomb := filepath.Join(dir, "zipbomb.docx")
	writeZip(t, bomb, map[string]string{"word/document.xml": strings.Repeat("A", maxZipEntryBytes+1)})
	// Entry flood: more entries than maxZipEntries, rejected at open.
	flood := filepath.Join(dir, "entryflood.docx")
	files := make(map[string]string, maxZipEntries+1)
	for i := 0; i < maxZipEntries+1; i++ {
		files[fmt.Sprintf("part%04d", i)] = "x"
	}
	writeZip(t, flood, files)
	// Deep nesting: thousands of nested <w:p> elements with the text at the
	// bottom; xml.Decoder is iterative, so this must parse fine rather than
	// exhausting the stack.
	deep := filepath.Join(dir, "deepnesting.docx")
	const w = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
	deepXML := `<w:document xmlns:w="` + w + `">` +
		strings.Repeat(`<w:p>`, 5000) +
		`<w:r><w:t>deep</w:t></w:r>` +
		strings.Repeat(`</w:p>`, 5000) + `</w:document>`
	writeZip(t, deep, map[string]string{"word/document.xml": deepXML})
	return map[string]string{"bomb": bomb, "flood": flood, "deep": deep}
}

// TestAbuseFixtures_LimitRegression is the abuse-corpus regression net: the
// bomb and the flood must be rejected with the typed limit error, and deep
// nesting must recover with its content intact.
func TestAbuseFixtures_LimitRegression(t *testing.T) {
	fx := generateAbuseFixtures(t, t.TempDir())

	_, err := ReadStructuredKind(context.Background(), fx["bomb"], KindDOCX)
	if !errors.Is(err, ErrArchiveLimit) {
		t.Errorf("zip bomb: err = %v, want ErrArchiveLimit", err)
	}
	_, err = ReadStructuredKind(context.Background(), fx["flood"], KindDOCX)
	if !errors.Is(err, ErrArchiveLimit) {
		t.Errorf("entry flood: err = %v, want ErrArchiveLimit", err)
	}
	res, err := ReadStructuredKind(context.Background(), fx["deep"], KindDOCX)
	if err != nil {
		t.Fatalf("deep nesting: unexpected error %v", err)
	}
	if !strings.Contains(res.Text, "deep") {
		t.Errorf("deep nesting: text %q missing expected content", res.Text)
	}
}
